### ISSUE TITLE
[Gameplay/Pantalla de Controles] Error con sprite del jugador y boton de pausa

### ISSUE THREAD

**Issue by frankvega2010** [InsaneFury/flappybird#2]
En la pantalla de los controles, si el jugador toca el boton de pausa y despues empieza la partida (tocando la barra espaciadora) el juego empieza poniendose en pausa y con el sprite del jugador alterado como en la siguiente imagen: 

![controls scheme bug on gameplay](https://user-images.githubusercontent.com/43391619/47575808-49c72d80-d919-11e8-97fc-284f333f5856.jpg)

**Comment by InsaneFury** [comment]
Already fixed on #6
