### ISSUE TITLE
Bug en botones

### ISSUE THREAD

**Issue by cusumdt** [InsaneFury/flappybird#7]
#Bug de overlap en los botones

- Al posicionar el mouse entre dos botones, se genera la animación de ambos. Cuidado! también al hacer click se cumplen las funciones de ambos.(esto pasa tanto en el menu, como en la pausa y el game over)
![overlap](https://user-images.githubusercontent.com/43677937/47576749-a4618900-d91b-11e8-96be-14d8fcfdce1d.png)

**Comment by InsaneFury** [comment]
Fixed #1
